### ISSUE TITLE
bad get_bearing() results

### ISSUE THREAD

**Issue by PauwelsYoran** [RigacciOrg/py-qmc5883l#3]
I connected a qmc5883l to my raspberry pi and tried to read the bearing using your library. When do I this i only get values between 70 and 120 deg. Do you have an idea if this maybe is a wiring or code problem?

**Comment by RigacciOrg** [comment]
Try the **get_bearing_raw()** function instead, just to see if there is some problem into the calibration algorithm.
I don't think about a **wiring problems**, otherwise you should experience overall reading problems.
Be sure to make a **complete turn** (360 degrees) of the sensor, while keeping its **X-Y plane flat**, when you read the values.

**Comment by Vitaha** [comment]
Looks like the lines 179-181 here https://github.com/RigacciOrg/py-qmc5883l/blob/master/py_qmc5883l/__init__.py#L177 should be 
`            x1 = x * c[0][0] + y * c[0][1] + c[0][2]`
`            y1 = x * c[1][0] + y * c[1][1] + c[1][2]`
`            z1 = x * c[2][0] + y * c[2][1] + c[2][2]`
because c -- is affine transformation that maps projective X-Y plane to projective X-Y plane. Last column of matrix c is just a displacement in flat plane and [x1, y1, z1] shouldn't depend on z-coordinate from 3-d vector field.

**Comment by RigacciOrg** [comment]
I think you are quite right in finding a bug in the code. My multiplication should be correct (need to apply corrections eventually to x, y and z), but I suspect to have **missed to add the origin offset**. I'm working on the report of another user, I hope to come back in a few days and (maybe) fix the code.
Thanks!

**Comment by EParisot** [comment]
Maybe you should try to use the magneto far from RPi, I had similar behaviour while keeping the sensor close from RPi... A few cm should do the trick...

**Comment by EParisot** [comment]
Vitaha, Your point should be correct anyway...

**Comment by RigacciOrg** [comment]
I just pushed a change. Now **get_magnet()** function returns only (X, Y) calibrated coordinates, not Z. This is because the **calibration** parameter is expected to be a 2d horizontal (X, Y) transformation matrix.
The previous version returned badly wrong values, especially when the raw values have large offsets from the (0, 0) origin. This change should fix the bug.

**Comment by Vitaha** [comment]
https://github.com/RigacciOrg/py-qmc5883l/blob/4fc9b1210769c7581bd60d66353c6586a8a1a25a/py_qmc5883l/__init__.py#L194
Minor flaw: now here should be [x, y].
Thanks for fix.
